name: deployAPI.yml
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.actor == github.repository_owner }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/backend:latest ./backend

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/backend:latest

      - name: Trigger Render Deployment
        env:
          deploy_url: ${{secrets.RENDER_DEPLOY_HOOK}}
        run: |
          curl "$deploy_url"

